### PR TITLE
Efl updates

### PR DESCRIPTION
**Pull request by Stefan-Schmidt**
Updating build system instructions and released versions.

### CODE REVIEW

**Comment by Stefan-Schmidt** [comment]
ping

**Comment by lvc** [comment]
Thank you!

**Comment by Stefan-Schmidt** [comment]
Hmm, there seems to be some problems with library detection in the automated builds:
https://abi-laboratory.pro/index.php?view=timeline&l=efl

1.22.5, 1.22.6 and 1.24.0 seems to have the problem.

On my local builds that worked as expected. Could you have a look?

**Comment by Stefan-Schmidt** [comment]
Would you prefer that I fill a github issue for this instead?

**Comment by bsdhw** [comment]
In 1.24.0 it tries to sudo install something and therefore failed to create report.

**Comment by bsdhw** [comment]
`Installing /tmp/.../build/efl-1.24.0/build_dir/meson-private/eet-cxx.pc to /home/.../efl/1.24.0/lib64/pkgconfigError executing command as another user: Not authorized`

**Comment by Stefan-Schmidt** [comment]
Thanks for taking the time to have a look.

Indeed we are doing a ninja install at the end of our build script. The other build scripts I looked into are doing the same though and I assumed it would be needed. Its a normal ninja install without sudo though.

What also baffles me is that this would only make problems on the 1.24.0, 1.22.5 and 1.22.6 builds but all the others are working fine.

**Comment by Stefan-Schmidt** [comment]
ok, digging around a bit more I can reproduce the problem the problem with 1.24 (not with the earlier ones, though). It tries to escalate the privileges during install. I will see what we have there.

**Comment by Stefan-Schmidt** [comment]
Mystery solved. We have two dbus and systems service files which get installed outside of the given prefix (based on the dirs needed for dbsu and systemd). Easy enough to work around for this build script. Will prepare a pull request soon.

**Pull request merged**
